# Generated by Django 5.2.5 on 2025-08-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
