# Generated by Django 5.2.5 on 2025-09-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
