# Generated by Django 5.2.5 on 2025-09-05 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
