# Generated by Django 5.2.5 on 2025-09-05 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_userinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinquiry',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userinquiry',
            name='verification_token',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
